services:
  - body: >-
      提供中餐、西餐
    icon: fa-cutlery
    title: 餐厅
  - body: >-
      提供大型会议展览服务，场地300平米
    icon: fa-bullhorn
    title: 会议服务
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-plus
    title: Room Setup
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-music
    title: Audio/Visuals
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-print
    title: Printing
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-wifi
    title: WiFi
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-map-signs
    title: Floor Planning
  - body: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
      eiusmod       tempor incididunt
    icon: fa-car
    title: Parking
