services:
  - body: >-
      提供中餐、西餐
    icon: fa-cutlery
    title: 餐厅
  - body: >-
      提供大型会议展览服务，场地300平米
    icon: fa-bullhorn
    title: 会议服务
  - body: >-
      提供室内体育场地
    icon: fa-plus
    title: 活动中心
  - body: >-
      提供量贩式KTV
    icon: fa-music
    title: KTV
  - body: >-
      提供海报、横幅打印服务
    icon: fa-print
    title: 打印服务
  - body: >-
      提供免费WIFI
    icon: fa-wifi
    title: WiFi
  - body: >-
      专业导游解说
    icon: fa-map-signs
    title: 导游
  - body: >-
      免费停车场
    icon: fa-car
    title: 停车
